TogethER/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('application.urls')),
    path('admin/', admin.site.urls),
]

application/urls.py
from django.urls import path

from . import views

app_name = 'application'
urlpatterns = [

    # ekran startowy
    path('', views.index, name='index'),

    # lista wszystkich ER
    # niezalogowani widzą tylko listę
    # zalogowani mogą zaznaczać i odznaczać, w których pokojach byli
    # przy każdym widać: kwadracik do zaznaczania, ew. ikonkę (zdjęcie), nazwę ER, nazwę firmy, miasto, ew. adres, ew. krótki opis
    path('escaperoomy/', views.escaperooms, name = 'escaperooms'),
    
    # lista wszystkich użytkowników
    path('uzytkownicy/', views.users, name = 'users'),

    # znajomi gracze (można przeglądać, dodawać i usuwać ze znajomych)
    path('znajomi/', views.buddies, name = 'buddies'),

    # historia odwiedzin
    # dotychczasowe wyjścia ze znajomymi (widać, w jakich pokojach się było i z kim)
    path('historia/', views.history, name = 'history'),

    #planowane wyjścia (zarówno te, które mają już decyzję, jak i te, które jeszcze czekają na decyzję)
    path('planowane/', views.planned, name = 'planned'),

    # ekran rejestracji użytkownika
    path('rejestracja/', views.registration, name = 'registration'),

    # ekran logowania użytkownika
    path('logowanie/', views.login, name = 'login'),

    # ekran logowania użytkownika
    path('wylogowanie/', views.logout, name = 'logout'),

    # edycja istniejącego wyjścia (zapraszanie znajomych, wybór ER)
    path('wyjscie/<int:goingout_id>/', views.goingOut, name ='goingout'),

    # tworzenie nowego wyjścia (przekierowanie do edycji wyjścia)
    path('newgoingout/', views.newGoingOut, name ='newgoingout'),

    # profil użytkownika (dowolnego)
    path('profil/<int:user_id>/', views.profile, name ='profile'),
]

application/models.py
from django.db import models

class EscapeRoom(models.Model):
	name = models.CharField(max_length = 255)
	description = models.CharField(max_length = 255)
	company = models.CharField(max_length = 255) # firma
	url = models.CharField(max_length = 1024) # link do LockMe
	def __str__(self):
		return '"' + self.name + '"'

class User(models.Model):
	username = models.CharField(max_length = 32)
	passwordHash = models.CharField(max_length = 255)
	visited = models.ManyToManyField(EscapeRoom, related_name="visitors") # osoby, które odwiedziły dany escape room (sic!)
	buddies = models.ManyToManyField("self", related_name="buddies")

	def __str__(self):
		return '"' + self.username + '"'
    
class GoingOut(models.Model):
	organisator = models.ForeignKey(User, on_delete = models.CASCADE, related_name="organisedGoingOuts")
	participants = models.ManyToManyField(User, related_name="goingOuts")
	decision = models.ForeignKey(EscapeRoom, on_delete = models.CASCADE, null = True)

application/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse

from .models import EscapeRoom, GoingOut, User


def getMe(request):
	try:
		return User.objects.get(id=request.session['user_id'])
	except (KeyError, User.DoesNotExist):
		return None

def index(request):
	return render(request, 'application/index.html', {'me': getMe(request)})

def history(request):
    return HttpResponse("Tutaj będzie historia odwiedzin.")

def registration(request):

	# jeśli użytkownik pierwszy raz otwiera stronę z rejestracją (przed wysłaniem formularza)
	if 'username' not in request.POST:
		return render(request, 'application/registration.html', {})

	# jeśli nazwa użytkownika jest pusta (użytkownik zostawił puste pole)
	if not request.POST['username']:
		return render(request, 'application/registration.html', {
            'error_message': "Nazwa użytkownika nie może być pusta.",
        })

	# jeśli powtarza się nazwa użytkownika
	if User.objects.filter(username=request.POST['username']): 
		user = User.objects.get(username=request.POST['username']) # NOWE
		return render(request, 'application/registration.html', {
			'error_message_exists': request.POST['username'],
			'user': user,
		})

	# jeśli hasło jest za krótkie (użytkownik zostawił puste pole lub wpisał za krótkie hasło)
	if len(request.POST['password']) <3:
		return render(request, 'application/registration.html', {
            'error_message': "Hasło jest za krótkie. Wybierz hasło długości co najmniej 3 znaków.",
        })

	newUser = User()
	newUser.username = request.POST['username']
	newUser.passwordHash = request.POST['password']
	newUser.save()

	return HttpResponseRedirect(reverse('application:index'))


def login(request):

	if 'username' not in request.POST:
		return render(request, 'application/login.html', {})

	try:
		user = User.objects.get(username=request.POST['username'])
		if user.passwordHash != request.POST['password']:
			raise Exception('Invalid password')
		request.session['user_id'] = user.id
		return HttpResponseRedirect(reverse('application:index'))
	except:
		return render(request, 'application/login.html', {'error_message': "Nieprawidłowa nazwa użytkownika lub hasło."})

def logout(request):
    try:
        del request.session['user_id']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('application:index'))



def escaperooms(request):

	if 'user_id' not in request.session:
		return render(request, 'application/escaperooms.html', {
			'escaperooms': EscapeRoom.objects.all(),
		})

	me = User.objects.get(id=request.session['user_id'])

	if 'escaperooms_changes' in request.POST: # jeśli kliknięto "Zapisz zmiany"
		# lista id odwiedzonych escape roomów
		visitedIdList = [int(s) for s in request.POST.getlist('escaperooms[]')]
		me.visited.set([EscapeRoom.objects.get(id = i) for i in visitedIdList])
		me.save()

		return HttpResponseRedirect(reverse('application:escaperooms'))

	visited = me.visited.all()

	return render(request, 'application/escaperooms.html', {
		'escaperooms': EscapeRoom.objects.all(),
		'me': getMe(request),
		'visited': visited,
		'which_escape_rooms': request.POST.get('which_escape_rooms', 'all'),
	})


def goingOut(request, goingout_id):

	me = getMe(request)
	if not me:
		return render(request, 'application/index.html', {})

	go = GoingOut.objects.get(id = goingout_id)

	if 'chosen_escaperoom' in request.POST:
		escapeRoom = EscapeRoom.objects.get(id = request.POST['chosen_escaperoom'])
		go.decision = escapeRoom
		go.save()


	visited_by_participants = EscapeRoom.objects.none() # pusty queryset

	
	# escape roomy, w których chociaż jeden uczestnik wydarzenia już był
	for participant in go.participants.all():
		visited_by_participants = visited_by_participants.union(participant.visited.all())
	
	unvisited = EscapeRoom.objects.all().difference(visited_by_participants)

	modified = False
	
	def tryAddParticipant(key):
		if key in request.POST and request.POST[key] != "":
			participant = User.objects.get(username = request.POST[key])
			go.participants.add(participant)
			nonlocal modified
			modified = True
	
	try:
		tryAddParticipant('participant_name_text')
		tryAddParticipant('participant_name_list')
	except User.DoesNotExist:
		return render(request, 'application/goingout.html', {
			'go': go,
			'participant_error_message': "Taki użytkownik nie istnieje.",
			'unvisited': unvisited,
			'me': me,
		})
	if modified:
		go.save()
		return HttpResponseRedirect("/wyjscie/" + str(go.pk))

	if 'delete_event' in request.POST:
		go.delete()
		return HttpResponseRedirect(reverse('application:planned'))


	if 'reset_decision' in request.POST:
		go.decision = None
		go.save()
		return HttpResponseRedirect(reverse('application:goingout', kwargs={'goingout_id': goingout_id}))


	return render(request, 'application/goingout.html', {
		'go': go,
		'unvisited': unvisited,
		'me': me,
	})


def newGoingOut(request):
	go = GoingOut()

	go.organisator = getMe(request)
	if not go.organisator:
		return HttpResponseRedirect(reverse('application:index'))

	go.save()
	go.participants.add(go.organisator)
	go.save()

	return HttpResponseRedirect("/wyjscie/" + str(go.pk))


def planned(request):

	me = getMe(request)
	if not me:
		return HttpResponseRedirect(reverse('application:index'))

	planned_goingouts = me.goingOuts.all()
	return render(request, 'application/planned.html', {
		'planned_goingouts': planned_goingouts.all(),
		'me': me,
	})

def buddies(request):
	
	me = getMe(request)
	if not me:
		return HttpResponseRedirect(reverse('application:index'))

	if 'buddy_name' in request.POST:
		try:
			buddy = User.objects.get(username = request.POST['buddy_name'])
			if buddy == me:
				return render(request, 'application/buddies.html', {
					'me_error_message': "Niestety nie możesz sam siebie dodać do znajomych :(",
					'me': me,
				})
		except User.DoesNotExist:
			return render(request, 'application/buddies.html', {
				'buddy_error_message': "Taki użytkownik nie istnieje.",
				'me': me,
			})
		me.buddies.add(buddy)
		me.save()
		return HttpResponseRedirect(reverse('application:buddies'))

	return render(request, 'application/buddies.html', {
		'me': me,
	})

def profile(request, user_id):

	me = getMe(request)

	try:
		user = User.objects.get(id = user_id)
	except User.DoesNotExist:
		raise Http404("Użytkownik nie istnieje.")

	visited_user = user.visited.all()
	visited_me = me.visited.all()
	commonERs = visited_user.intersection(visited_me)
	commonERs_len = len(commonERs)

	if 'add_buddies' in request.POST:
		me.buddies.add(user)
		me.save()
		return HttpResponseRedirect(reverse('application:profile', kwargs={'user_id': user_id}))

	if 'delete_buddies' in request.POST:
		me.buddies.remove(user)
		me.save()
		return HttpResponseRedirect(reverse('application:profile', kwargs={'user_id': user_id}))

	return render(request, 'application/profile.html', {
		'me': me,
		'user': user,
		'commonERs': commonERs,
		'commonERs_len': commonERs_len,
	})

def users(request):
	
	me = getMe(request)
	if not me:
		return HttpResponseRedirect(reverse('application:index'))

	return render(request, 'application/users.html', {
		'me': me,
		'users': User.objects.all()
	})

application/templates/application/buddies.html
<!DOCTYPE html>

<html>
<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'application/style.css' %}">
</head>

<body>
	{% include "application/main_menu.html" %}
	<div class="page">

		<form action="{% url 'application:buddies' %}" method="post">
			{% csrf_token %}
			<label for="buddy_name">Wpisz nazwę użytkownika, którego chcesz zaprosić do znajomych: </label>
			<input id="buddy_name" type="text" name="buddy_name" value="">
			{% if buddy_error_message %}
				<div class="error">{{buddy_error_message}}</div>
			{% endif %}
			{% if me_error_message %}
				<div class="error">{{me_error_message}}</div>
			{% endif %}
			<br/>
			<input class="button" type="submit" value="Zaproś">
		</form>

		<p>Twoi znajomi:
			{% for buddy in me.buddies.all %}
				<strong><a href = {% url 'application:profile' buddy.id %}>{{buddy.username}}</a></strong>{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</p>
	</div>
</body>
</html>

application/templates/application/escaperooms.html
<!DOCTYPE html>

<html>
<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'application/style.css' %}">
</head>

<body>
	{% include "application/main_menu.html" %}
	<div class="page">
		{% if not me %}
			<p class="header"><strong> Lista escape roomów </strong></p>
				<ul>
					{% for escaperoom in escaperooms %}
					<li> {{escaperoom.name}} (<em><a href="{{escaperoom.url}}">zobacz na LockMe</a></em>)</li>
					{% endfor %}
				</ul>

		{% else %}

			<p class="header">Zaznacz odwiedzone pokoje:</p>

			<form action="{% url 'application:escaperooms' %}" method="post">
				{% csrf_token %}
				Pokaż
				<select name="which_escape_rooms" onchange="this.form.submit()"> {# wstawka z JavaScriptu #}
					<option value="all"
						{% if which_escape_rooms == "all" %} selected {% endif %}>wszystkie</option>
					<option value="visited"
						{% if which_escape_rooms == "visited" %} selected {% endif %}>odwiedzone</option>
					<option value="unvisited"
						{% if which_escape_rooms == "unvisited" %} selected {% endif %}>nieodwiedzone</option>
				</select>
				escape roomy.
				{# <input class="button" type="submit" value="Zatwierdź"> #}
			</form>

			<form action="{% url 'application:escaperooms' %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="escaperooms_changes" value="1">

				{% for escaperoom in escaperooms %}
					<div {% if which_escape_rooms == 'unvisited' and escaperoom in visited %}hidden{% endif %}
						{% if which_escape_rooms == 'visited' and escaperoom not in visited %}hidden{% endif %}>
						<label>
							<input type="checkbox" name="escaperooms[]" value={{escaperoom.id}}
								{% if escaperoom in visited %}checked{% endif %}>
							{{escaperoom.name}}
						</label>
						(<em><a href="{{escaperoom.url}}">zobacz na LockMe</a></em>)<br/>
					</div>
				{% endfor %}
				<br/>
				<input class="button" type="submit" value="Zapisz zmiany">
			</form>
		{% endif %}
	</div>
</body>

</html>

application/templates/application/goingout.html
<!DOCTYPE html>

<html>

<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'application/style.css' %}">
</head>

<body>
	{% include "application/main_menu.html" %}
	<div class="page">
		<p>
			Osoby, które idą na to wydarzenie:
			{% for participant in go.participants.all %}
			<strong><a href = {% url 'application:profile' participant.id %}>{{participant.username}}</a></strong>{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</p>

		<p>Organizator: <strong><a href = {% url 'application:profile' go.organisator.id %}>{{go.organisator.username}}</a></strong></p><br/>

		<form action="{% url 'application:goingout' go.id %}" method="post">
			{% csrf_token %}
			Wpisz nazwę użytkownika, którego chcesz zaprosić:
			<input type="text" name="participant_name_text" value="">
			lub wybierz znajomego z listy:
			<select name="participant_name_list">
				<option value="" selected>(wybierz użytkownika)</option> {% comment %} TERAZ DOPISANE {% endcomment %}
				{% for user in me.buddies.all %}
					<option>{{user.username}}</option>
				{% endfor %}
			</select>
			{% if participant_error_message %}
				<div class="error">{{participant_error_message}}</div>
			{% endif %}
			<br/>
			<input class="button" type="submit" value="Zaproś">
		</form>
		<br/>
		<br/>

		<p>
			Proponowane escape roomy:<br/>
			<form action="{% url 'application:goingout' go.id %}" method="post">
				{% csrf_token %}
				{% for escaperoom in unvisited.all %}
					<input type="radio" name="chosen_escaperoom" id="escaperoom{{forloop.counter}}"
						value="{{ escaperoom.id }}"  {% if go.decision == escaperoom %} checked {% endif %}>
					<label for="escaperoom{{ forloop.counter }}">{{escaperoom.name}}</label>
				{% empty %}
					Brak escape roomów, do których wszyscy mogą pójść :( <br/>
				{% endfor %}
				<br>
				<input class="button" type="submit" value="Wybierz">
			</form>

			<form action="{% url 'application:goingout' go.id %}" method="post">
				{% csrf_token %}
				<input class="button" type="submit" name="reset_decision" value="Jeszcze się nie zdecydowałem">
			</form>

			<br/>
			<br/>
			<form action="{% url 'application:goingout' go.id %}" method="post">
				{% csrf_token %}
				<input class="button" type="submit" name="delete_event" value="Usuń wydarzenie">
			</form>
		</p>
	</div>
</body>

</html>

application/templates/application/index.html
<!DOCTYPE html>

<html>

<head>
	<title>TogethER – strona główna</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'application/style.css' %}">
</head>

<body>
	{% include "application/main_menu.html" %}
</body>

</html>

application/templates/application/login.html
<!DOCTYPE html>

<html>

<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'application/style.css' %}">
</head>

<body>
	{% include "application/main_menu.html" %}
	<div class="page">
		<form action="{% url 'application:login' %}" method="post">
			{% csrf_token %}
			<label for="username">Nazwa użytkownika: </label>
			<input id="username" type="text" name="username" value="">

			<br/>
			<label for="password">Hasło: </label>
			<input id="password" type="password" name="password" value="">

			<br/>
			<input type="submit" value="Zaloguj">
		</form>

		{% if error_message %}
			<div class="error">{{ error_message }}</div>
		{% endif %}
	</div>
</body>

</html>

application/templates/application/main_menu.html
<ul class="menu">

	<li class="menu"><a href = "{% url 'application:escaperooms' %}">Lista ER</a></li>&nbsp


{% if me %}
	<li class="menu"><a href = "{% url 'application:buddies' %}">Znajomi</a></li>&nbsp

	<li class="menu"><a href = "{% url 'application:users' %}">Użytkownicy</a></li>&nbsp

	<li class="menu"><a href = "{% url 'application:planned' %}">Planowane wyjścia</a></li>&nbsp
	
	{% comment %} 
	<li class="menu"><a href = "{% url 'application:history' %}">Historia wizyt</a></li>&nbsp
	{% endcomment %}

	<li class="menu right">Zalogowany jako <a href = {% url 'application:profile' me.id %}>{{me.username}}</a></li>
	<li class="menu right"><a href = "{% url 'application:logout' %}">WYLOGUJ</a></li>
{% else %}
	<li class="menu right"><a href = "{% url 'application:registration' %}">ZAREJESTRUJ</a></li>&nbsp
	<li class="menu right"><a href = "{% url 'application:login' %}">ZALOGUJ</a></li>
{% endif %}
</ul><br/><br/><br/><br/>

application/templates/application/planned.html
<!DOCTYPE html>

<html>
<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'application/style.css' %}">
</head>

<body>
	{% include "application/main_menu.html" %}
	<div class="page">
		<p class="header">Planowane wyjścia do escape roomów: </p>
		<form action="{% url 'application:newgoingout' %}" method="post">
			{% csrf_token %}
			<input class="button" type="submit" value="Utwórz nowe wyjście">
		</form>
		<br/>

		<table align="center">
			{% for goingout in planned_goingouts %}
			<tr>
				<td>
					<ul class="frame">
						<li>Uczestnicy:
							{% for participant in goingout.participants.all %}
							<strong><a href = {% url 'application:profile' participant.id %}>{{participant.username}}</a></strong>{% if not forloop.last %}, {% endif %}
							{% endfor %}
						<li>Organizator: <strong><a href = {% url 'application:profile' goingout.organisator.id %}>{{ goingout.organisator.username }}</a></strong></li>
						<li>Escape room: {% if not goingout.decision %} brak decyzji {% else %} <strong>{{ goingout.decision.name }}{% endif %}</strong></li>
					</ul>
				</td>
				<td>
					<form action="{% url 'application:goingout' goingout.id %}" method="post">
						{% csrf_token %}
						<input class="button" type="submit" value="Edytuj wyjście">
					</form>
				</td>
			</tr>
			{% endfor %}
		</table>
	</div>
</body>
</html>

application/templates/application/profile.html
<!DOCTYPE html>

<html>

<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'application/style.css' %}">
</head>

<body>
	{% include "application/main_menu.html" %}
	<div class="page">
		{% if user == me %}
			<p class="header">Twój profil</p>
			</p>Napisz coś o sobie.</p>
			<input class="button" type="submit" value="Zmień hasło">

		{% elif user != me %}
			<p class="header">Profil użytkownika <strong>{{user.username}}</strong></p>
			<br/>
			<br/>
			{% if commonERs_len == 0 %}
				<p>Nie ma escape roomu, w którym i Ty, i {{user.username}} byliście.</p>
			{% else %}
				<p>Byliście w {{commonERs_len}} tych samych escape roomach:</p>
			{% endif %}
			<ul>
				{% for ER in commonERs%}
					<li>{{ER.name}}(<em><a href = {{ER.url}}>Zobacz na LockMe</a></em>)</li>
				{% endfor %}
			</ul>

			{% comment %}
				<p>Planujecie pójść wspólnie do XXXXXX escape roomów: (+ wymienić)</p>
				<p>Planujecie iść do XXXXXXXXX tych samych escape roomów: (+ wymienić)</p>
			{% endcomment %}


			{% if user in me.buddies.all %}
				<form action="{% url 'application:profile' user.id %}" method="post">
					{% csrf_token %}
					<input type="hidden" name="delete_buddies">
					<input class="button" type="submit" value="Usuń ze znajomych">
				</form>
			{% else %}
				<form action="{% url 'application:profile' user.id %}" method="post">
					{% csrf_token %}
					<input type="hidden" name="add_buddies">
					<input class="button" type="submit" value="Dodaj do znajomych">
				</form>
			{% endif %}

		{% endif %}
	</div>
</body>

application/templates/application/registration.html
<!DOCTYPE html>

<html>
<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'application/style.css' %}">
</head>

<body>
    {% include "application/main_menu.html" %}
    <div class="page">
        <form action="{% url 'application:registration' %}" method="post">
            {% csrf_token %}
            <label for="username">Nazwa użytkownika: </label>
            <input id="username" type="text" name="username" value="">

            <br/>
            <label for="password">Hasło: </label>
            <input id="password" type="password" name="password" value="">

            <br/>
            <input type="submit" value="Zarejestruj">
        </form>

        {% if error_message_exists %}
            <div class="error">Już istnieje użytkownik <a href = {% url 'application:profile' user.id %}>{{user.username}}.</div>
        {% elif error_message %}
            <div class="error">{{ error_message }}</div>
        {% endif %}
    </div>
</body>

</html>

application/templates/application/users.html
<!DOCTYPE html>

<html>
<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'application/style.css' %}">
</head>

<body>
	{% include "application/main_menu.html" %}
	<div class="page">
		<p>Wszyscy użytkownicy TogethER (w kolejności od dołączenia):
			{% for user in users %}
				<strong><a href = {% url 'application:profile' user.id %}>{{user.username}}</a></strong>{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</p>
	</div>
</body>
</html>